from run_options.run_without_animation import run_without_animation
from run_options.run_animation_2d import run_animation_2d
from run_options.run_animation_3d import run_animation_3d
from run_options.run_prove_rotational_variance import prove_rotational_variance